"""中医外科疮疡病种数据(90 病种 · 13 章)"""
from typing import Any

# 每项:treat 字段为 治则/内治/外治(来自书本)
DISEASES: list[dict[str, Any]] = [
    # ============ 第一章 疔疮 ============
    {"name": "印堂疔", "category": "疔", "aliases": ["眉心疔", "丑心疔", "面风毒", "印堂疔", "风眉疔"],
     "location": "两眉中心(印堂穴)", "morphology": "初起疮顶有粟粒样脓头,形小根硬,根盘收束,如钉丁之状",
     "characteristics": "时痒时麻,红肿热痛,重者上至前额、下及目眶鼻根,甚至头面俱肿。",
     "differential": "与鼻疔、额疔鉴别:均属颜面疔疮,部位不同。", "prognosis": "颜面疔疮,挤压不当易走黄。",
     "western_equiv": "两眉中间之疖肿或痈", "source": "《治疗大全·卷上》", "is_dangerous": True,
     "treat": {"治则": "清热解毒", "内治": "五味消毒饮加减", "外治": "油调膏或玉露散外敷"}},
    {"name": "眼角疔", "category": "疔", "aliases": [],
     "location": "眼角内侧", "morphology": "头如粟,色黄白,疗根坚硬,根盘高突收束,色嫩红",
     "characteristics": "肿势蔓延鼻根、上下眼睑,眼开合受限,为火毒炽盛。", "differential": "与鼻根疔、迎香疔鉴别:部位在眼角。",
     "prognosis": "颜面疔疮,易走黄。", "western_equiv": "眼角部疖肿/蜂窝织炎", "source": None, "is_dangerous": True,
     "treat": {"治则": "提脓拔毒", "内治": "五味消毒饮、黄连解毒汤加减", "外治": "九一丹或八二丹置疮顶,外敷油调膏、玉露散"}},
    {"name": "鼻根疔", "category": "疔", "aliases": [],
     "location": "鼻根部", "morphology": "鼻根部粟粒大脓头,坚硬根深,周围略肿,色红",
     "characteristics": "脓头尚未破溃,火毒不剧。", "differential": "与鼻疔鉴别:部位在鼻根。", "prognosis": "同颜面疔疮。",
     "western_equiv": "鼻根部疖肿", "source": None, "is_dangerous": True,
     "treat": {"治则": "清热解毒", "内治": "五味消毒饮加减", "外治": "油调膏、玉露散外敷"}},
    {"name": "鼻疔", "category": "疔", "aliases": ["鼻尖疔"],
     "location": "鼻外或鼻孔内", "morphology": "鼻尖部粟米大脓头,黄白相兼,根深坚硬",
     "characteristics": "位于颜面危险三角区,脓头破溃、脓栓未脱,根盘赤肿胀,易走黄。", "differential": "与鼻根疔鉴别:鼻根疔在鼻根部。",
     "prognosis": "危险三角区,易走黄危及生命。", "western_equiv": "鼻部疖肿", "source": None, "is_dangerous": True,
     "treat": {"治则": "提脓解毒", "内治": "五味消毒饮加减", "外治": "油调膏、玉露散外敷"}},
    {"name": "鼻翼疔", "category": "疔", "aliases": ["鼻窦疔"],
     "location": "鼻翼(鼻穴部)", "morphology": "鼻翼处粟粒样脓头,根盘未收束,肿势延向鼻部及面部",
     "characteristics": "脓头增大,脓栓外突,即将脱落。", "differential": "与鼻疔鉴别:部位在鼻翼。", "prognosis": "颜面疔疮。",
     "western_equiv": "鼻翼部疖肿", "source": None, "is_dangerous": True,
     "treat": {"治则": "清热解毒", "内治": "五味消毒饮加减", "外治": "油调膏、玉露散外敷"}},
    {"name": "人中疔", "category": "疔", "aliases": ["龙泉疔"],
     "location": "人中穴", "morphology": "约稻粒大,红热高肿,有黄白色脓头,根深痒痛",
     "characteristics": "根脚收束,色嫩红,周围肿势不剧,属初期;处理不当易走黄。", "differential": "与鼻疔、迎香疔鉴别:部位在人中穴。",
     "prognosis": "易走黄。", "western_equiv": "上唇疖肿", "source": None, "is_dangerous": True,
     "treat": {"治则": "清热解毒", "内治": "五味消毒饮加减", "外治": "油调膏、玉露散外敷"}},
    {"name": "迎香疔", "category": "疔", "aliases": ["迎香毒"],
     "location": "迎香穴(鼻翼旁)", "morphology": "粟米粒大脓头,根脚坚硬,根盘收束高突,色嫩赤",
     "characteristics": "连及鼻翼上唇,火毒炽盛,最易走黄。", "differential": "与人中疔、鼻疔鉴别:部位在迎香穴。",
     "prognosis": "最易走黄。", "western_equiv": "鼻翼旁疖肿", "source": "《治疗大全·卷上》", "is_dangerous": True,
     "treat": {"治则": "清热解毒", "内治": "五味消毒饮加减", "外治": "油调膏、玉露散外敷"}},
    {"name": "额疔", "category": "疔", "aliases": ["额骨疔", "赤面疔"],
     "location": "两额部位", "morphology": "中央小粟粒大脓头,盘硬根深,如钉丁之状,肿势局限高起",
     "characteristics": "初期火毒不剧;渐加剧则脓头虽溃而肿势未减,周围赤肿。", "differential": "与眼角疔、印堂疔鉴别:部位在两额。",
     "prognosis": "颜面疔疮,注意防走黄。", "western_equiv": "额部疖肿", "source": "《疡医准绳·卷一》", "is_dangerous": True,
     "treat": {"治则": "清热解毒", "内治": "五味消毒饮加减", "外治": "油调膏、玉露散外敷"}},
    {"name": "虎须疔", "category": "疔", "aliases": [],
     "location": "人中两旁", "morphology": "始有脓头,盘硬根深,逐渐高肿,肿势加剧",
     "characteristics": "脓头破溃,脓栓未脱,火毒外泄未尽形成溃疡。", "differential": "与人中疔鉴别:部位在人中两旁。",
     "prognosis": None, "western_equiv": "唇痈、蜂窝织炎", "source": "《疡医准绳》", "is_dangerous": True,
     "treat": {"治则": "清热解毒", "内治": "五味消毒饮加减", "外治": "生肌散、生肌玉红膏掺提毒散外敷"}},
    {"name": "唇疔", "category": "疔", "aliases": ["鱼口风", "反唇疔", "锁口疔"],
     "location": "上下唇部", "morphology": "初起如粟,痒痛不休,逐渐肿胀,唇部外翻,开口困难",
     "characteristics": "其形甚微,其毒极深,色或白或赤,火毒炽盛肿势蔓延。", "differential": "与地仓疔、颊疔鉴别:部位在唇。",
     "prognosis": "颜面疔疮,易走黄。", "western_equiv": "唇部疖痈或蜂窝织炎", "source": "《疡医大全·卷十四》", "is_dangerous": True,
     "treat": {"治则": "清热解毒,提脓", "内治": "五味消毒饮、黄连解毒汤,配服蟾酥丸、西黄丸", "外治": "油调膏、玉露散外敷,脓栓不脱用九一丹、八二丹"}},
    {"name": "地仓疔", "category": "疔", "aliases": [],
     "location": "地仓穴(面颊口角旁)", "morphology": "面颊处生疔,脓头破溃,脓汁溢于疮口",
     "characteristics": "可向周围扩散,致开口不利。", "differential": "与唇疔鉴别:部位在地仓穴。", "prognosis": "颜面疔疮。",
     "western_equiv": "面颊部疖肿", "source": None, "is_dangerous": True,
     "treat": {"治则": "清热解毒", "内治": "五味消毒饮、黄连解毒汤加减", "外治": "油调膏、玉露散外敷"}},
    {"name": "颊疔", "category": "疔", "aliases": ["承浆疔"],
     "location": "颊部(或承浆穴)", "morphology": "颊部起脓头,逐渐高肿,根盘坚硬色赤",
     "characteristics": "向下唇蔓延,灼热疼痛。", "differential": "与唇疔、地仓疔鉴别:部位在颊部。", "prognosis": "颜面疔疮。",
     "western_equiv": "颊部疖肿", "source": None, "is_dangerous": True,
     "treat": {"治则": "清热解毒", "内治": "五味消毒饮、黄连解毒汤加减", "外治": "油调膏、玉露散外敷"}},
    {"name": "领疔", "category": "疔", "aliases": ["下颌疔"],
     "location": "下颌处", "morphology": "下颌处初起粟粒大脓头,根深如钉丁,逐渐红肿热痛",
     "characteristics": "常蔓延腮部、颊部及颌下,脓成按之有波动感。", "differential": "与颊疔鉴别:部位在下颌。",
     "prognosis": "颜面疔疮。", "western_equiv": "下颌部疖肿", "source": None, "is_dangerous": True,
     "treat": {"治则": "清热解毒", "内治": "五味消毒饮加减", "外治": "油调膏、玉露散外敷"}},
    {"name": "沿爪疔", "category": "疔", "aliases": ["蛇眼疔", "代指", "甲沟炎"],
     "location": "指甲沟(甲根两旁)", "morphology": "初起指甲一侧边缘轻度红肿热痛,可蔓延对侧或甲下",
     "characteristics": "3-5日成脓,脓积甲下可见黄白色脓液,重者甲根掀起。", "differential": "与蛇头疔鉴别:沿爪疔在甲沟。",
     "prognosis": "轻浅。", "western_equiv": "甲沟炎", "source": None, "is_dangerous": False,
     "treat": {"治则": "清热利湿解毒", "内治": "五福化毒丹、梅花点舌丹", "外治": "一效膏、金黄膏外敷,成脓切开排脓"}},
    {"name": "蛇头疔", "category": "疔", "aliases": ["天蛇毒", "天蛇头", "水蛇头"],
     "location": "指端", "morphology": "指端红肿,形如蛇头,色红灼热,疼痛剧烈",
     "characteristics": "皮坚内连筋骨,成脓后难破外达,易内伤筋骨,合并腐骨。", "differential": "与蛇腹疔鉴别:蛇头疔在指端。",
     "prognosis": "易损伤筋骨,可致末节腐脱。", "western_equiv": "化脓性指头炎", "source": "《疡医准绳·卷二》", "is_dangerous": False,
     "treat": {"治则": "清热解毒", "内治": "仙方活命饮、五味消毒饮加减", "外治": "水调散、金黄散、玉露散外敷,成脓切开引流"}},
    {"name": "蛇腹疔", "category": "疔", "aliases": ["蛇肚疔", "鱼肚疔", "鳅肚疔"],
     "location": "手指腹侧面", "morphology": "指腹肿胀,如蛇腹之状,灼热疼痛,伸屈困难",
     "characteristics": "中央透脓色白,按之有波动感,为脓已成。", "differential": "与蛇头疔鉴别:蛇腹疔在指腹。",
     "prognosis": "不及时治疗可损伤筋骨。", "western_equiv": "手指化脓性感染", "source": "《疡医准绳·卷三》", "is_dangerous": False,
     "treat": {"治则": "清热解毒", "内治": "五味消毒饮、黄连解毒汤、仙方活命饮加减", "外治": "初期水调散、玉露散、金黄散外敷;中期切开排脓"}},
    {"name": "蛇节疔", "category": "疔", "aliases": ["时节疔", "钉节天蛇", "病蛇节"],
     "location": "指(趾)骨节间", "morphology": "指骨节间生疔,根深坚硬,四周肿胀,绕指俱肿",
     "characteristics": "色或黄或紫,疮顶破溃形成溃疡。", "differential": "与蛇头疔鉴别:蛇节疔在骨节间。",
     "prognosis": "可损及筋骨。", "western_equiv": "手指化脓性感染", "source": "《治疗大全·蛇节疔》", "is_dangerous": False,
     "treat": {"治则": "清热解毒", "内治": "仙方活命饮、五味消毒饮加减", "外治": "水调散、金黄散外敷,成脓切开"}},
    {"name": "手丫疔", "category": "疔", "aliases": ["手丫刺", "丫叉毒", "虎口疔", "合谷毒"],
     "location": "指丫(虎口处)", "morphology": "指间高肿,中央黄白色脓头,盘硬根深",
     "characteristics": "初起如粟,渐大如豆,焮热疼痛,伸指剧痛。", "differential": "与蛇腹疔鉴别:手丫疔在指间。",
     "prognosis": None, "western_equiv": "手指间隙感染", "source": "《疡科心得集·卷上》", "is_dangerous": False,
     "treat": {"治则": "清热解毒", "内治": "五味消毒饮、黄连解毒汤、仙方活命饮加减", "外治": "水调散、玉露散、金黄散外敷"}},
    {"name": "托盘疔", "category": "疔", "aliases": ["掌心毒", "病穿掌", "手心痛", "穿板疔", "托盘疔"],
     "location": "手掌心", "morphology": "初起水泡,逐渐增大,皮色变黑,有波动感,周围坚硬肿痛",
     "characteristics": "初起坚硬起泡,其泡明亮者易挑之。", "differential": "与蛇头疔鉴别:托盘疔在掌心。",
     "prognosis": None, "western_equiv": "手掌间隙感染", "source": "《疡科心得集·卷上》", "is_dangerous": False,
     "treat": {"治则": "清热解毒", "内治": "仙方活命饮、五味消毒饮加减", "外治": "切开排脓,外敷玉露散"}},
    {"name": "红丝疔", "category": "疔", "aliases": ["红丝血箭疔", "血丝疔", "赤疔", "红线疔"],
     "location": "手足(沿淋巴管走行)", "morphology": "原发疔疮,沿肢体出现一条红线,由远端向上走窜",
     "characteristics": "红线灼热压痛,轻者抵腋下,重者达胸前,可并发走黄。", "differential": "与一般疔疮鉴别:红丝疔有特征性红线。",
     "prognosis": "重者毒入营血走黄。", "western_equiv": "急性淋巴管炎", "source": "《疡医准绳·卷二》", "is_dangerous": True,
     "treat": {"治则": "清热解毒", "内治": "仙方活命饮、五味消毒饮、黄连解毒汤", "外治": "沿红线挑刺放血,外敷水调散、金黄膏"}},
    {"name": "疔疮走黄", "category": "疔", "aliases": ["走黄"],
     "location": "全身(由疔疮毒散入血)", "morphology": "疔头忽然陷黑,肿势蔓延,疮缘起水泡,色先紫后黑",
     "characteristics": "高热、神昏、谵语,为疔毒走散入营血、内攻脏腑之危候。", "differential": "与内陷鉴别:走黄为疔毒走散,内陷为正虚毒陷。",
     "prognosis": "危重,可危及生命。", "western_equiv": "毒血症、败血症、脓血症", "source": "《疮疡经验全书·暑疔》", "is_dangerous": True,
     "treat": {"治则": "清热解毒,凉血开窍", "内治": "清营汤、犀角地黄汤加减,神昏安宫牛黄丸", "外治": "原发疔疮提脓拔毒"}},

    # ============ 第二章 疖 ============
    {"name": "热疖", "category": "疖", "aliases": ["有头疖", "无头疖"],
     "location": "全身皮肤毛囊部位", "morphology": "红色结节,高突,中央黄白色脓头,根浅局限,约1寸",
     "characteristics": "有头疖见于毛囊部位,无头疖见于皮肤较厚部位,脓出即愈。", "differential": "与痈鉴别:疖范围小根浅,痈范围较大。",
     "prognosis": "轻浅易愈。", "western_equiv": "毛囊及皮脂腺或汗腺急性化脓性炎症", "source": None, "is_dangerous": False,
     "treat": {"治则": "清热解毒,化湿消肿", "内治": "五福化毒丹、犀角化毒丸、雄黄解毒丸", "外治": "油调膏、金黄膏、玉露散外敷"}},
    {"name": "暑疖", "category": "疖", "aliases": ["热疖"],
     "location": "全身(夏秋季)", "morphology": "同热疖,发于暑热季节",
     "characteristics": "夏季发病,因暑湿火毒所致。", "differential": "与热疖鉴别:有明显季节性。",
     "prognosis": "轻浅。", "western_equiv": "毛囊炎/疖", "source": None, "is_dangerous": False,
     "treat": {"治则": "清暑利湿,清热解毒", "内治": "五福化毒丹、犀角化毒丸", "外治": "油调膏、金黄膏外敷"}},
    {"name": "多发性疖", "category": "疖", "aliases": ["发际疖", "坐板疮"],
     "location": "项后、背部及臀部", "morphology": "身体某处或全身同时发生多个疖,反复发作",
     "characteristics": "簇集成群红色小结节,此起彼伏,缠绵不愈。", "differential": "与蝼蛄疖鉴别:多发性疖在项后/背/臀。",
     "prognosis": "缠绵不愈。", "western_equiv": "疖病", "source": None, "is_dangerous": False,
     "treat": {"治则": "祛风清热,利湿解毒", "内治": "防风通圣散加减", "外治": "油调膏、玉露膏、千捶膏外敷,三黄洗剂外擦"}},
    {"name": "蝼蛄疖", "category": "疖", "aliases": ["蟠拱头", "蟮拱头"],
     "location": "头部(小儿多发)", "morphology": "头部大小不等疖肿,相互连通,形似蝼蛄拱头",
     "characteristics": "溃后疮口难敛,或一处将愈它处又发,重者满布头部深腐骨质。", "differential": "与多发性热疖鉴别:专指头部多发性疖。",
     "prognosis": "顽固难愈,可深腐骨质。", "western_equiv": "小儿头部疖肿及脓肿性穿凿性毛囊周围炎", "source": "《外科正宗·蟠拱头》", "is_dangerous": False,
     "treat": {"治则": "清热解毒,扶正透脓", "内治": "五神汤加减", "外治": "空腔十字切开,提毒散或八二丹撒疮口,外敷油调膏"}},
    {"name": "坐板疖", "category": "疖", "aliases": ["坐板疮"],
     "location": "臀部", "morphology": "臀部散在粟粒大疖肿,聚集成群,流溢脓水",
     "characteristics": "脾经湿热湿毒郁久所致,彼愈此发缠绵不休。", "differential": "与蝼蛄疖鉴别:坐板疖在臀部。",
     "prognosis": None, "western_equiv": "臀部多发性疖肿", "source": "《外科启玄·坐板疮》", "is_dangerous": False,
     "treat": {"治则": "清热利湿,解毒消肿", "内治": "五神汤或健脾除湿汤合四妙散加减", "外治": "油调膏、千捶膏外敷"}},

    # ============ 第三章 痈 ============
    {"name": "颈痈", "category": "痈", "aliases": ["天疽", "夹喉痈", "痰毒"],
     "location": "颈部两侧", "morphology": "初起肿块如鸡卵大,表无脓头,焮热疼痛,继红肿高大",
     "characteristics": "风热挟痰所致,多见于小儿,伴发热恶寒。", "differential": "与瘰疬鉴别:颈痈红肿热痛易成脓,瘰疬不红不热属阴证。",
     "prognosis": "一般易愈。", "western_equiv": "颈部急性化脓性淋巴结炎", "source": "《素问·病能论》", "is_dangerous": False,
     "treat": {"治则": "疏风清热,化痰散结;成脓托里透脓", "内治": "牛蒡解肌汤或银翘散加减,成脓仙方活命饮", "外治": "水调散、金黄散、玉露散外敷,成脓切开排脓"}},
    {"name": "结喉痈", "category": "痈", "aliases": ["锁喉痈", "猛盖", "盘颈痰毒", "锁喉毒"],
     "location": "喉结(颈前正中)", "morphology": "颈前肿块,红热疼痛,吞咽痛甚,高肿皮薄色赤",
     "characteristics": "重者肿势绕喉,上至颈关下延胸前,伴发热口渴吞咽不利。", "differential": "与颈痈鉴别:结喉痈在颈前正中位置较深。",
     "prognosis": "重者可致呼吸困难。", "western_equiv": "颈前蜂窝织炎", "source": "《医宗金鉴·结喉痈》", "is_dangerous": True,
     "treat": {"治则": "散风清热,化痰托毒", "内治": "五味消毒饮加减", "外治": "初期水调散、金黄散外敷;成脓切开排脓引流"}},
    {"name": "耳根痈", "category": "痈", "aliases": ["耳根毒", "耳后痈"],
     "location": "耳根部位", "morphology": "耳垂后方肿势高突,状如伏鼠,皮紧光亮,焮红灼热",
     "characteristics": "外感风热或耳后皮脂腺瘤染毒而发。", "differential": "与颈痈鉴别:部位在耳后。",
     "prognosis": None, "western_equiv": "耳后皮脂腺瘤感染或急性化脓性淋巴结炎", "source": "《疮疡经验全书》", "is_dangerous": False,
     "treat": {"治则": "清热解毒,托里透脓", "内治": "五味消毒饮加减", "外治": "切开引流,撒八二丹或七三丹,外敷水调散、玉露膏"}},
    {"name": "腋痈", "category": "痈", "aliases": ["夹肢痈", "腋前痈", "腋后痈"],
     "location": "腋窝部", "morphology": "腋下高肿,焮热疼痛,动则痛剧,表无脓头,根盘散漫",
     "characteristics": "肝脾二经为患,初起皮色不变漫肿无头,日久方痛。", "differential": "与腋疽鉴别:腋痈阳证,腋疽阴证。",
     "prognosis": None, "western_equiv": "腋窝部急性化脓性淋巴结炎", "source": "《外科正宗·卷四》", "is_dangerous": False,
     "treat": {"治则": "清热解毒,消肿散结", "内治": "仙方活命饮加减", "外治": "水调散外敷"}},
    {"name": "腹壁痈", "category": "痈", "aliases": ["腹皮痈", "肚痈", "中脘痈", "少腹痈"],
     "location": "腹壁部位", "morphology": "腹壁红肿高突,焮热疼痛,根盘紧束,皮薄光亮",
     "characteristics": "严重者脓成不泄,易内溃透膜。", "differential": "与腹壁疽鉴别:腹壁痈浅表,腹壁疽深。",
     "prognosis": "重者内溃透膜。", "western_equiv": "腹壁化脓性感染", "source": None, "is_dangerous": False,
     "treat": {"治则": "初期清热解毒散瘀消肿,中期托里透脓", "内治": "初期黄连解毒汤,中期合托里透脓汤", "外治": "初期水调散、金黄散外敷,中期切开引流"}},
    {"name": "脐痈", "category": "痈", "aliases": ["脐痈毒"],
     "location": "脐部", "morphology": "脐部红肿外突,高肿无头,色红或紫红,皮薄光亮",
     "characteristics": "心脾湿热火毒结于脐中,溃后脓色污,甚者成瘘。", "differential": "与腹壁痈鉴别:部位在脐。",
     "prognosis": "可成脐瘘。", "western_equiv": "脐部感染/卵黄管残留症", "source": "《疮疡经验全书·卷三》", "is_dangerous": False,
     "treat": {"治则": "泻火解毒,利湿托毒", "内治": "黄连解毒汤合五苓散加减", "外治": "切开引流,外敷一效膏,脐瘘宜手术"}},
    {"name": "胯腹痈", "category": "痈", "aliases": ["跨马痈", "骑马痈", "骗马痈"],
     "location": "胯腹(腹股沟)部", "morphology": "腹股沟处红肿,中央高突,根盘散大,灼热跳痛",
     "characteristics": "按之有波动感,髋关节活动不利,伴寒热,脓已成。", "differential": "与股白肿鉴别:胯腹痈为淋巴结化脓。",
     "prognosis": None, "western_equiv": "腹股沟浅部急性化脓性淋巴结炎", "source": "《中医外科学》", "is_dangerous": False,
     "treat": {"治则": "清热利湿,托毒外出", "内治": "黄连解毒汤合萆薢渗湿汤加穿山甲、皂角刺", "外治": "切开引流,四周外敷水调散、金黄散"}},
    {"name": "腰痈", "category": "痈", "aliases": ["腰疽"],
     "location": "腰部", "morphology": "腰部肿疡,高肿,按之波动,皮色光亮",
     "characteristics": "一般痈的证候。", "differential": "与肾俞发鉴别:肾俞发为有头疽。",
     "prognosis": None, "western_equiv": "腰部蜂窝织炎", "source": "《外科启玄·卷五》", "is_dangerous": False,
     "treat": {"治则": "托里透脓,清热解毒", "内治": "托里透脓汤加减", "外治": "切开引流,外敷水调散、金黄散"}},
    {"name": "臀痈", "category": "痈", "aliases": ["坐马痈", "上马痈", "下马痈"],
     "location": "臀部", "morphology": "臀部漫肿微红,形大如盘,结块坚硬,根盘散漫",
     "characteristics": "病位较深,初起漫肿无头,溃脓较慢,走路不便。", "differential": "与坐板疖鉴别:臀痈范围大。",
     "prognosis": None, "western_equiv": "臀部蜂窝织炎", "source": "《外科理例》", "is_dangerous": False,
     "treat": {"治则": "初期清热解毒行气散结,中期托里透脓", "内治": "初期仙方活命饮,中期黄连解毒汤合托里透脓汤", "外治": "初期水调散、金黄散外敷,中期切开引流"}},
    {"name": "肛痈", "category": "痈", "aliases": ["便痈", "肛门痈", "脏毒", "盘肛痈"],
     "location": "肛门周围", "morphology": "肛门周围高肿,焮热疼痛,不易外溃",
     "characteristics": "溃后易成肛漏。", "differential": "与子痈鉴别:部位在肛门。",
     "prognosis": "溃后易成肛漏。", "western_equiv": "肛周脓肿", "source": "《医门补要》", "is_dangerous": False,
     "treat": {"治则": "清热解毒,活血散瘀", "内治": "黄连解毒汤加减", "外治": "水调散、金黄膏、双柏散外敷"}},
    {"name": "子痈", "category": "痈", "aliases": ["外肾痈", "肾子肿"],
     "location": "睾丸", "morphology": "睾丸突然肿大剧痛,形似鸭卵,不得触近",
     "characteristics": "牵及肾系及少腹疼痛,溃后脓稠收口缓慢。", "differential": "与子痫鉴别:子痈急性,子痫慢性结核。",
     "prognosis": None, "western_equiv": "睾丸炎及附睾炎", "source": "《外科证治全书》", "is_dangerous": False,
     "treat": {"治则": "清肝泻热,托里排脓", "内治": "龙胆泻肝汤加皂角刺、蒲公英等", "外治": "切开引流,外敷水调散"}},
    {"name": "臂痈", "category": "痈", "aliases": ["膊痈", "竞痈"],
     "location": "上臂", "morphology": "上臂内侧红肿,中央高突,灼热,腋下有肿大淋巴结",
     "characteristics": "同一般痈。", "differential": "与上臂疽鉴别:臂痈浅,上臂疽有头。",
     "prognosis": None, "western_equiv": "上臂蜂窝织炎", "source": None, "is_dangerous": False,
     "treat": {"治则": "清热解毒,消肿散结", "内治": "仙方活命饮加减", "外治": "水调散、金黄散外敷"}},
    {"name": "肘痈", "category": "痈", "aliases": ["肘后痈", "发艾毒"],
     "location": "肘部", "morphology": "肘部赤肿,高肿无头,向四周蔓延,结块质硬",
     "characteristics": "轻者限局肘部,重者肿绕肘部,关节屈伸不利。", "differential": "与腕痈鉴别:部位在肘。",
     "prognosis": None, "western_equiv": "肘部急性蜂窝织炎", "source": "《疡医准绳》", "is_dangerous": False,
     "treat": {"治则": "初期疏风散结凉血解毒,中期托里透脓", "内治": "初期仙方活命饮加丹皮、桃仁,中期托里透脓汤", "外治": "初期水调散、金黄膏外敷,中期切开引流"}},
    {"name": "腕痈", "category": "痈", "aliases": ["手屈发", "鼓槌风"],
     "location": "手腕部", "morphology": "腕部漫肿,散漫不收,表面无头,微红",
     "characteristics": "外伤染毒所致,腕关节屈伸受限。", "differential": "与肘痈鉴别:部位在腕。",
     "prognosis": None, "western_equiv": "腕部蜂窝织炎", "source": "《疡医准绳》", "is_dangerous": False,
     "treat": {"治则": "清热解毒,消肿散瘀", "内治": "仙方活命饮加减", "外治": "油调膏、金黄膏或玉露膏外敷"}},
    {"name": "手背痈", "category": "痈", "aliases": ["手背发", "手发背", "蜘蛛背"],
     "location": "手背部", "morphology": "手背部漫肿色红,边界不清,痛如鸡啄,灼热",
     "characteristics": "切开后脓血粘稠,脓毒外泄肿胀渐消。", "differential": "与托盘疔鉴别:手背痈在手背。",
     "prognosis": None, "western_equiv": "手背部急性化脓性炎症", "source": None, "is_dangerous": False,
     "treat": {"治则": "清热解毒,和营透托", "内治": "仙方活命饮加减", "外治": "玉露膏、水调散外敷"}},
    {"name": "大腿痈", "category": "痈", "aliases": ["股阳痈", "伏兔发", "赤施"],
     "location": "大腿", "morphology": "大腿高肿色红,焮热疼痛,境界清楚,质地较硬",
     "characteristics": "与一般痈相似。", "differential": "与小腿痈鉴别:部位在大腿。",
     "prognosis": None, "western_equiv": "大腿急性化脓性蜂窝织炎", "source": "《疡医大全》", "is_dangerous": False,
     "treat": {"治则": "清热解毒,消瘀透脓", "内治": "仙方活命饮加减", "外治": "水调散、金黄散、玉露膏外敷"}},
    {"name": "小腿痈", "category": "痈", "aliases": ["鱼肚痈", "腓腨发", "偏马坠"],
     "location": "小腿", "morphology": "小腿外侧焮红漫肿,边界不清,色赤拒按,灼热疼痛",
     "characteristics": "与一般痈相似。", "differential": "与大腿痈鉴别:部位在小腿。",
     "prognosis": None, "western_equiv": "小腿急性化脓性炎症", "source": None, "is_dangerous": False,
     "treat": {"治则": "清热解毒,消瘀透脓", "内治": "仙方活命饮加减", "外治": "水调散、金黄散、玉露膏外敷"}},
    {"name": "足背痈", "category": "痈", "aliases": ["足背发", "足发背", "脚背发"],
     "location": "足背部", "morphology": "足背外侧红肿高突,表面无头,向周围扩展,灼热疼痛",
     "characteristics": "结块质硬,边界不清,触痛剧烈,活动不利,伴发热恶寒。", "differential": "与手背痈鉴别:部位在足背。",
     "prognosis": None, "western_equiv": "足背部急性化脓性感染", "source": None, "is_dangerous": False,
     "treat": {"治则": "清热利湿,解毒散瘀", "内治": "仙方活命饮合萆薢渗湿汤", "外治": "水调散、金黄散外敷"}},

    # ============ 第四章 有头疽 ============
    {"name": "脑疽", "category": "有头疽", "aliases": ["对口疽", "对口疮", "落头疽", "偏脑疽"],
     "location": "脑后项部", "morphology": "初起即有多个粟粒样脓头,红肿灼热,向深部及周围扩展",
     "characteristics": "溃后呈蜂窝状,易引起毒邪内陷。", "differential": "与颈痈鉴别:脑疽多发项后范围大有多个脓头。",
     "prognosis": "重者易内陷。", "western_equiv": "项痈(蜂窝织炎)", "source": "《外科理例》", "is_dangerous": True,
     "treat": {"治则": "初期散风清热和营托毒,中期清热凉血解毒透脓,后期调补气血", "内治": "初期仙方活命饮,中期合黄连解毒汤,后期八珍汤或十全大补汤", "外治": "油调膏、金黄膏外敷,中期十字切开排脓掺八二丹或七三丹,后期生肌散"}},
    {"name": "脑顶疽", "category": "有头疽", "aliases": ["百会疽", "透脑疽", "佛顶疽"],
     "location": "脑顶部(百会穴处)", "morphology": "脑顶部肿胀,有多个脓头,逐渐高肿",
     "characteristics": "溃破后脓液畅泄,腐肉渐尽,肉芽红活。", "differential": "与脑疽鉴别:部位在头顶。",
     "prognosis": None, "western_equiv": "头部痈、蜂窝织炎", "source": None, "is_dangerous": True,
     "treat": {"治则": "清热解毒,托毒生肌", "内治": "透脓散加减", "外治": "油调膏、金黄膏、玉露膏外敷,脓尽生肌散"}},
    {"name": "额疽", "category": "有头疽", "aliases": ["髭疽", "赤疽"],
     "location": "额头部(或鬓角)", "morphology": "额角处肿块中央破溃,多个脓栓外脱",
     "characteristics": "火毒渐消脓毒大泄,腐肉脱落新肉生长,因皮肉浅薄愈合较慢。", "differential": "与额疔鉴别:额疽范围大有头。",
     "prognosis": None, "western_equiv": "面部痈", "source": None, "is_dangerous": True,
     "treat": {"治则": "清火解郁,解毒消肿", "内治": "柴胡清肝汤合五味消毒饮加减", "外治": "油调膏、金黄散掺提毒散外敷"}},
    {"name": "缺盆疽", "category": "有头疽", "aliases": ["锁骨疽"],
     "location": "锁骨上缺盆处", "morphology": "缺盆上方高肿色赤,焮热红肿,境界清楚",
     "characteristics": "溃破后疮口呈蜂窝状,内有脓栓未脱,脓黄粘稠。", "differential": "与发背疽鉴别:部位在缺盆。",
     "prognosis": None, "western_equiv": "锁骨上痈", "source": None, "is_dangerous": False,
     "treat": {"治则": "清热泻火解毒,托里透脓", "内治": "仙方活命饮、透脓散加减", "外治": "金黄膏外敷,十字切开排脓掺八二丹"}},
    {"name": "发背疽", "category": "有头疽", "aliases": ["背疽", "搭背", "搭手", "上发背", "中发背", "下发背"],
     "location": "背部", "morphology": "背部肿块上有多个粟粒样脓头,焮红灼热,渐向周围扩大",
     "characteristics": "疮头腐烂形似蜂窝,重者气血两虚毒滞不化内陷。", "differential": "与脑疽鉴别:发背在背部,脑疽在项后。",
     "prognosis": "重者易内陷。", "western_equiv": "腰背部痈、蜂窝织炎", "source": None, "is_dangerous": True,
     "treat": {"治则": "清热泻火解毒消肿,和营托毒透脓", "内治": "仙方活命饮加减,中期透脓散,虚证托里消毒散", "外治": "千捶膏贴疮头,四周油调膏或金黄膏外敷,十字切开排脓"}},
    {"name": "髂腰疽", "category": "有头疽", "aliases": ["髂腰痈"],
     "location": "腰腹之间", "morphology": "髂腰部肿块,疮形高肿,灼热疼痛,初起即有多个脓头",
     "characteristics": "境界清楚,中央坏死内有脓栓,为酿脓期。", "differential": "与发背疽鉴别:部位在髂腰部。",
     "prognosis": None, "western_equiv": "髂腹痈", "source": None, "is_dangerous": False,
     "treat": {"治则": "清热解毒,托里透脓", "内治": "仙方活命饮、透脓散加减", "外治": "金黄膏外敷,十字切开排脓"}},
    {"name": "肾俞发", "category": "有头疽", "aliases": ["连肾发"],
     "location": "腰部肾俞穴附近", "morphology": "肾俞穴处肿块,多个脓头破溃烂为一疮",
     "characteristics": "肾阴亏虚火毒蕴结,四周疮色紫暗坚硬,脓栓不脱。", "differential": "与腰痈鉴别:肾俞发为有头疽。",
     "prognosis": None, "western_equiv": "腰部痈", "source": None, "is_dangerous": False,
     "treat": {"治则": "清热解毒,托里透脓", "内治": "托里消毒散、清营化毒汤加减", "外治": "金黄膏外敷,十字切开排脓"}},
    {"name": "莲子发", "category": "有头疽", "aliases": ["蜂窝发", "莲蓬发"],
     "location": "腰部", "morphology": "多处脓头同时起发,相连成片,状若莲子",
     "characteristics": "高肿有多个脓头,连为一疮,根盘逐渐扩大。", "differential": "与发背疽鉴别:莲子发多脓头相连成片。",
     "prognosis": None, "western_equiv": "痈、蜂窝织炎", "source": None, "is_dangerous": False,
     "treat": {"治则": "清热解毒,托里透脓", "内治": "仙方活命饮、透脓散加减", "外治": "金黄膏外敷,切开排脓"}},
    {"name": "腹壁疽", "category": "有头疽", "aliases": ["小腹疽", "横痃", "少腹疽"],
     "location": "腹壁", "morphology": "腹壁肿块皮色暗红,向四周扩展,根盘较大,多个粟粒状脓头",
     "characteristics": "化腐成脓,中央多处脓头溃破呈蜂窝状。", "differential": "与腹壁痈鉴别:腹壁疽深有头。",
     "prognosis": None, "western_equiv": "腹壁痈", "source": None, "is_dangerous": False,
     "treat": {"治则": "清热解毒,托里透脓", "内治": "仙方活命饮、透脓散加减", "外治": "金黄膏外敷,切开排脓"}},
    {"name": "腋疽", "category": "有头疽", "aliases": ["米疽", "商疽"],
     "location": "腋窝部", "morphology": "初起腋部有结块,不红不痛,数月后酿化成脓皮色转红",
     "characteristics": "溃后脓水清稀挟败絮,多形成漏管瘘道,常年不敛。", "differential": "与腋痈鉴别:腋疽阴证成瘘。",
     "prognosis": "形成漏管常年不敛。", "western_equiv": "淋巴结炎及结核混合感染", "source": "《灵枢·痈疽》", "is_dangerous": False,
     "treat": {"治则": "初期疏肝养血解郁化痰,中期托毒透脓,后期滋阴养血", "内治": "初期逍遥散合二陈汤,中期合五味消毒饮,后期香贝养荣汤", "外治": "初期阳和解凝膏,中期切开排脓外敷一效膏,后期黑药条插漏管"}},
    {"name": "上臂疽", "category": "有头疽", "aliases": [],
     "location": "上臂内侧", "morphology": "上臂内侧肿块,多个粟米样脓头,中央脓头腐烂成疮面",
     "characteristics": "肿胀未消。", "differential": "与臂痈鉴别:上臂疽有头。",
     "prognosis": None, "western_equiv": "上臂痈", "source": None, "is_dangerous": False,
     "treat": {"治则": "托毒排脓,清热解毒", "内治": "透脓散加减", "外治": "切开排脓,外敷油调膏、金黄膏掺九一丹"}},
    {"name": "前臂疽", "category": "有头疽", "aliases": [],
     "location": "前臂内侧中部", "morphology": "前臂中部肿起,中央高突,皮色暗红,多个脓头",
     "characteristics": "焮热疼痛,垂手剧痛。", "differential": "与上臂疽鉴别:部位在前臂。",
     "prognosis": None, "western_equiv": "前臂痈", "source": None, "is_dangerous": False,
     "treat": {"治则": "清热解毒,和营消肿", "内治": "仙方活命饮加桑枝、姜黄", "外治": "油调膏、千捶膏外敷"}},
    {"name": "腕疽", "category": "有头疽", "aliases": [],
     "location": "腕背部", "morphology": "腕背部红肿热痛,初起有粟米样脓头",
     "characteristics": "脓溃后皮肉腐烂,腐肉脱落生新长肉。", "differential": "与腕痈鉴别:腕疽有头。",
     "prognosis": None, "western_equiv": "腕部痈", "source": None, "is_dangerous": False,
     "treat": {"治则": "托毒排脓,清热解毒", "内治": "透脓散加减", "外治": "切开排脓,外敷油调膏掺九一丹"}},
    {"name": "股内疽", "category": "有头疽", "aliases": [],
     "location": "大腿内侧", "morphology": "大腿内侧肿块,初起多个脓头,红肿范围较大",
     "characteristics": "脓腐渐尽,肉色暗红,愈合较慢。", "differential": "与大腿痈鉴别:股内疽有头。",
     "prognosis": None, "western_equiv": "大腿痈", "source": None, "is_dangerous": False,
     "treat": {"治则": "初期清热解毒和营消肿,后期补气养血生肌长肉", "内治": "初期仙方活命饮,后期人参养荣汤加减", "外治": "红油膏掺九一丹或白玉膏掺生肌散"}},
    {"name": "股后疽", "category": "有头疽", "aliases": [],
     "location": "大腿后侧", "morphology": "大腿后侧肿疡,脓腐已尽,四周新肉生长",
     "characteristics": "逐渐愈合,属后期。", "differential": "与股内疽鉴别:部位在股后。",
     "prognosis": None, "western_equiv": "大腿痈", "source": None, "is_dangerous": False,
     "treat": {"治则": "初期清热解毒和营消肿,后期补气养血生肌长肉", "内治": "初期仙方活命饮,后期人参养荣汤加减", "外治": "红油膏掺九一丹或白玉膏掺生肌散"}},
    {"name": "股前疽", "category": "有头疽", "aliases": [],
     "location": "大腿前侧", "morphology": "大腿前侧肿块,有多个粟米样脓头,红肿焮热",
     "characteristics": "有头疽发于股前,证治同股内、股后疽。", "differential": "与股内疽、股后疽鉴别:部位在股前。",
     "prognosis": None, "western_equiv": "大腿痈", "source": None, "is_dangerous": False,
     "treat": {"治则": "初期清热解毒和营消肿,后期补气养血托毒生肌", "内治": "初期仙方活命饮,后期人参养荣汤加减", "外治": "红油膏掺九一丹或白玉膏掺生肌散"}},
    {"name": "膝疽", "category": "有头疽", "aliases": [],
     "location": "膝部(内外侧)", "morphology": "膝外侧红肿,中央高突,皮色紫暗,多个粟米样脓头",
     "characteristics": "四周坚硬,界线不清,毒不外泄,酿脓迟缓。", "differential": "与股内疽鉴别:部位在膝。",
     "prognosis": None, "western_equiv": "膝部痈", "source": None, "is_dangerous": False,
     "treat": {"治则": "初期清热解毒和营消肿,成脓清热解毒托毒外泄", "内治": "初期仙方活命饮,成脓内托黄芪汤加减", "外治": "油调膏、红油膏掺九一丹"}},

    # ============ 第五章 无头疽 ============
    {"name": "附骨疽", "category": "无头疽", "aliases": ["骨痈", "贴骨痈", "多骨疽", "咬骨疽"],
     "location": "筋骨(四肢长骨)", "morphology": "初起漫肿无头,疼痛彻骨,溃后脓水淋漓不易收口",
     "characteristics": "附筋着骨而生,好发于儿童四肢长骨,可成窦道伤筋蚀骨。", "differential": "与流痰鉴别:附骨疽为化脓性骨髓炎,流痰为骨结核。",
     "prognosis": "易伤筋骨,重者内陷。", "western_equiv": "化脓性骨髓炎", "source": "《千金方·卷二十二》", "is_dangerous": True,
     "treat": {"治则": "初期清热化湿行瘀通络,成脓和营托毒,溃后调补气血", "内治": "初期黄连解毒汤合五神汤,成脓加山甲皂刺,溃后八珍汤", "外治": "初期独角莲膏外敷,成脓切开排脓掺九一丹,脓尽生肌散"}},
    {"name": "胁肋疽", "category": "无头疽", "aliases": ["胁疽", "渊疽", "侠荣疽", "传心疽"],
     "location": "胁肋部(胸壁)", "morphology": "起病缓慢,漫肿无头,皮色不变,隐隐作痛",
     "characteristics": "溃后脓水清稀挟败絮,久不收口,病灶深达肋骨成瘘道。", "differential": "与附骨疽鉴别:胁肋疽为胸壁结核。",
     "prognosis": "久不愈,成瘘道。", "western_equiv": "胸壁结核", "source": None, "is_dangerous": True, "is_yang": False,
     "treat": {"治则": "初期清肝解郁化痰散结,成脓托里透脓,溃后调补气血", "内治": "初期柴胡清肝汤合二陈汤,成脓透脓散,溃后人参养荣汤", "外治": "初期阳和解凝膏,成脓穿刺排脓,形成瘘道黑药条插,脓尽生肌象皮膏"}},
    {"name": "足踝疽", "category": "无头疽", "aliases": ["内踝疽", "外踝疽", "穿踝疽", "鞋带疽"],
     "location": "足踝部", "morphology": "足踝处焮热肿胀疼痛,关节活动受限",
     "characteristics": "发于内踝称内踝疽,外踝称外踝疽,穿透者称穿踝疽。", "differential": "与足跟疽鉴别:部位在踝。",
     "prognosis": None, "western_equiv": "化脓性踝关节炎及足踝部感染", "source": None, "is_dangerous": False,
     "treat": {"治则": "清热利湿,和营解毒", "内治": "仙方活命饮合五神汤", "外治": "一效膏、金黄膏外敷"}},
    {"name": "足跟疽", "category": "无头疽", "aliases": ["跟疽"],
     "location": "足跟部", "morphology": "足跟部肿胀疼痛,成脓溃破,腐肉脱落显露跟骨",
     "characteristics": "脓汁时而黄白稠厚时而稀薄淋漓,肉芽生长极慢。", "differential": "与足踝疽鉴别:部位在跟。",
     "prognosis": "久不收口。", "western_equiv": "足跟部溃疡", "source": None, "is_dangerous": False, "is_yang": False,
     "treat": {"治则": "补肾益气,祛腐生肌", "内治": "补中益气汤合桂附地黄丸加减", "外治": "生肌白玉膏、生肌象皮膏掺生肌散"}},

    # ============ 第六章 瘰疬 ============
    {"name": "瘰疬", "category": "瘰疬", "aliases": ["老鼠疮", "疬子颈", "马刀侠瘿"],
     "location": "颈项、胸腋", "morphology": "颈部结块成串,累累如贯珠,不红不热,难消难溃难敛",
     "characteristics": "痰火或痰湿结于颈项,日久溃破脓汁稀薄挟败絮,甚成瘘道漏管。", "differential": "与颈痈鉴别:颈痈阳证易成脓,瘰疬阴证难消难溃。",
     "prognosis": "病程长,易成漏管。", "western_equiv": "颈部淋巴结结核", "source": "《灵枢·寒热》", "is_dangerous": False, "is_yang": False,
     "treat": {"治则": "初期疏肝化痰软坚散结,溃后养营化痰祛腐生肌", "内治": "初期逍遥散加减,后期香贝养荣汤加减", "外治": "初期独角莲膏、冲和散、阳和解凝膏,溃后五五丹、七三丹,漏管插二宝丹、黑药条"}},

    # ============ 第七章 乳痈 ============
    {"name": "乳痈", "category": "乳痈", "aliases": ["吹乳", "乳发", "内吹乳痈", "外吹乳痈"],
     "location": "乳房", "morphology": "乳房积乳胀大,内有肿块,焮热疼痛,红肿高大",
     "characteristics": "肝郁气滞乳汁郁积肝郁胃热,多见于初产妇产后3-4周。", "differential": "与乳岩鉴别:乳痈红肿热痛易成脓,乳岩坚硬如石不痛。",
     "prognosis": "及时治疗多消散或排脓而愈。", "western_equiv": "急性化脓性乳腺炎", "source": "《针灸甲乙经》", "is_dangerous": False,
     "treat": {"治则": "疏肝解郁通乳散结,成脓清热解毒托毒排脓", "内治": "瓜蒌牛蒡汤加减,成脓透脓散合五味消毒饮", "外治": "水调散、金黄膏外敷,成脓放射状切口切开排脓"}},
    {"name": "乳头破碎", "category": "乳痈", "aliases": ["乳头风", "乳头破裂", "乳头皲裂"],
     "location": "乳头", "morphology": "乳头部潮红、糜烂、皲裂、结痂,形如草莓",
     "characteristics": "肝火不得疏泄或婴儿咬破乳头,吸乳刺痛。", "differential": "与乳痈鉴别:乳头破碎在乳头。",
     "prognosis": "易致积乳。", "western_equiv": "乳头皲裂", "source": "《疡科心得集》", "is_dangerous": False,
     "treat": {"治则": "清泻肝火,祛湿生肌", "内治": "龙胆泻肝汤加减", "外治": "一效膏、生肌玉红膏、珍珠散外敷或蛋黄油外涂"}},
    {"name": "乳漏", "category": "乳痈", "aliases": ["乳房漏"],
     "location": "乳房", "morphology": "乳房溃后或手术损伤乳络,形成漏管,脓水淋漓不收口",
     "characteristics": "乳痈溃后引流不畅或乳络受损,日久成漏,时流脓水。", "differential": "与乳岩鉴别:乳漏为漏管,乳岩为肿块。",
     "prognosis": "难收口。", "western_equiv": "乳瘘", "source": None, "is_dangerous": False,
     "treat": {"治则": "补益气血,生肌收口", "内治": "八珍汤、人参养荣汤加减", "外治": "漏管插黑药条、三品一条枪,脓尽生肌散外敷"}},
    {"name": "乳癖", "category": "乳痈", "aliases": ["乳腺增生"],
     "location": "乳房", "morphology": "乳房肿块,大小不一,随情志消长,经前胀痛",
     "characteristics": "肝郁气滞痰凝,肿块可推移,经后减轻,属结块性乳病。", "differential": "与乳岩鉴别:乳癖肿块软可推移、随情志消长。",
     "prognosis": "良性,需随访。", "western_equiv": "乳腺增生", "source": None, "is_dangerous": False,
     "treat": {"治则": "疏肝理气,化痰散结", "内治": "逍遥散合四物汤加减,香贝养荣汤", "外治": "冲和膏外贴"}},
    {"name": "乳疬", "category": "乳痈", "aliases": ["男性乳房发育"],
     "location": "乳晕部", "morphology": "乳晕部结块,或胀痛,男性多见",
     "characteristics": "肝气郁结或肾气不充,乳晕部出现结块,属结块性乳病。", "differential": "与乳癖鉴别:乳疬在男性乳晕部。",
     "prognosis": "良性。", "western_equiv": "男性乳房异常发育", "source": None, "is_dangerous": False,
     "treat": {"治则": "疏肝理气,化痰软坚", "内治": "逍遥散加减,香贝养荣汤", "外治": "冲和膏外贴"}},
    {"name": "乳岩", "category": "乳痈", "aliases": ["乳石痈", "乳瘤", "石榴翻花发"],
     "location": "乳房", "morphology": "乳房结块坚硬如石,凹凸不平,推之不移,溃后状如菜花",
     "characteristics": "情志不畅肝脾两伤痰火互结,多发中年以上妇女,溃后外翻如菜花。", "differential": "与乳痈鉴别:乳岩坚硬不痛不红。",
     "prognosis": "恶候,可危及生命。", "western_equiv": "乳腺癌", "source": "《诸病源候论》", "is_dangerous": True, "is_yang": False,
     "treat": {"治则": "补益气血,软坚散结", "内治": "香贝养荣汤加减", "外治": "红油膏、一效膏掺海浮散外敷"}},

    # ============ 第八章 臁疮 ============
    {"name": "臁疮", "category": "臁疮", "aliases": ["裙边疮", "裤口疮", "老烂腿"],
     "location": "小腿下1/3", "morphology": "小腿胫骨部溃烂,疮口凹陷,边缘高起如缸口",
     "characteristics": "脾胃湿热下注,好发于静脉曲张者,肉色灰白,流滋稀薄脓水,久难敛易复发。", "differential": "与脱疽鉴别:臁疮为静脉性溃疡,脱疽为缺血性坏疽。",
     "prognosis": "病程长,易复发。", "western_equiv": "下肢静脉曲张并发慢性溃疡", "source": "《华佗神医秘传》", "is_dangerous": False,
     "treat": {"治则": "初期清热利湿活血化瘀,后期清热利湿补益气血", "内治": "初期三妙丸合萆薢渗湿汤,后期合十全大补汤、补中益气丸", "外治": "初期一效膏、金黄膏、青黛散,后期生肌散、一效散、提毒散,外敷生肌玉红膏"}},

    # ============ 第九章 丹毒 ============
    {"name": "丹毒", "category": "丹毒", "aliases": ["抱头火丹", "大头瘟", "腿游风", "流火", "赤游风"],
     "location": "头面、小腿多见", "morphology": "皮肤忽然变赤,色如涂丹,迅速蔓延成片,鲜红,境界清楚",
     "characteristics": "血分有热外感火毒,红斑按之退色,灼热疼痛,重者水泡,一般不化脓。", "differential": "与发(蜂窝织炎)鉴别:丹毒鲜红境界清楚不化脓。",
     "prognosis": "下肢丹毒易反复发作。", "western_equiv": "丹毒(溶血性链球菌感染)", "source": "《千金要方》", "is_dangerous": False,
     "treat": {"治则": "清热利湿,凉血解毒", "内治": "龙胆泻肝汤或黄连解毒汤合三妙丸加减", "外治": "水调散、金黄散外敷"}},

    # ============ 第十章 褥疮 ============
    {"name": "褥疮", "category": "褥疮", "aliases": ["席疮", "印疮"],
     "location": "骶尾、足跟、头枕部等受压部位", "morphology": "受压部位皮色暗红,继而溃烂成疮,经久难敛",
     "characteristics": "长期卧床气血亏虚肌肤失养,摩擦染毒而成。", "differential": "与冻疮鉴别:褥疮因久卧受压。",
     "prognosis": "重者深烂至骨。", "western_equiv": "褥疮", "source": "《外科启玄》", "is_dangerous": False, "is_yang": False,
     "treat": {"治则": "活血化瘀,清热解毒,补益气血", "内治": "初起气滞血瘀者桃红四物汤加减活血化瘀;蕴毒腐溃者五味消毒饮合桃红四物汤清热解毒;气血两虚收口期八珍汤、十全大补汤加减", "外治": "未溃者翻身按摩、活血酒外擦,已溃一效膏、红油膏掺九一丹,脓腐尽生肌象皮膏掺生肌散"}},

    # ============ 第十一章 冻疮 ============
    {"name": "冻疮", "category": "冻疮", "aliases": ["冻烂疮", "冻风", "水浸手", "战壕足"],
     "location": "手指、手背、足跟、足趾、耳廓等暴露部位", "morphology": "受冻部位红肿,瘙痒,皮色青紫,重者起水泡溃烂",
     "characteristics": "寒冷侵袭血脉凝滞,轻者肿胀痒痛,重者肌肤坏死损伤筋骨,易复发。", "differential": "与褥疮鉴别:冻疮因寒冷所致。",
     "prognosis": "易反复,天暖自愈。", "western_equiv": "冻伤", "source": "《诸病源候论》", "is_dangerous": False, "is_yang": False,
     "treat": {"治则": "温阳散寒,调和营卫", "内治": "桂枝加当归汤或当归四逆汤加减,黄酒为引", "外治": "小水泡外敷九一膏、红油膏,大水泡抽液后外敷"}},

    # ============ 第十二章 周围血管病 ============
    {"name": "脱疽", "category": "脱疽", "aliases": ["脱骨疽", "十指零落", "敦痈"],
     "location": "四肢末端(下肢多见)", "morphology": "患处发凉麻木,皮色暗红,疼痛剧烈,日久紫黑腐烂骨节脱落",
     "characteristics": "脾肾阳虚肝肾不足寒湿外受,多见于20-40岁吸烟男性。", "differential": "与臁疮鉴别:脱疽为缺血性坏疽。",
     "prognosis": "重者需截肢。", "western_equiv": "血栓闭塞性脉管炎", "source": "《灵枢·痈疽》", "is_dangerous": True, "is_yang": False,
     "treat": {"治则": "温经散寒,活血化瘀,清热解毒,补益气血", "内治": "寒湿型阳和汤、独活寄生汤,血瘀型桃红四物汤,热毒型四妙勇安汤,气血两虚型十全大补汤", "外治": "红灵酒外涂、熏洗药,干性坏疽无菌包扎,湿性三黄洗剂冲洗,生肌玉红膏外敷"}},
    {"name": "糖尿病坏疽", "category": "脱疽", "aliases": ["消渴病坏疽"],
     "location": "足趾、足背", "morphology": "足趾变黑溃烂,呈湿性坏疽,范围较大迅速蔓延",
     "characteristics": "素患消渴病,疮面脓水较多臭秽不堪。", "differential": "与脱疽鉴别:有糖尿病史。",
     "prognosis": "重者截肢。", "western_equiv": "糖尿病足坏疽", "source": None, "is_dangerous": True,
     "treat": {"治则": "清热利湿,解毒祛腐", "内治": "四妙勇安汤加减,配服消渴丸、降糖丹", "外治": "生肌玉红膏外敷,坏疽截除"}},
    {"name": "闭塞性动脉硬化坏疽", "category": "脱疽", "aliases": ["动脉硬化坏疽"],
     "location": "足趾、手指", "morphology": "趾(指)端变黑,呈干性坏疽,由小渐大,境界清楚",
     "characteristics": "好发50岁以上老年人,素有高血压动脉硬化,周围不红不肿疼痛剧烈。", "differential": "与脱疽鉴别:年龄大,动脉硬化。",
     "prognosis": "重者截肢。", "western_equiv": "闭塞性动脉硬化坏疽", "source": None, "is_dangerous": True, "is_yang": False,
     "treat": {"治则": "清热解毒,活血通络", "内治": "四妙勇安汤合桃红四物汤加减", "外治": "参照脱疽"}},
    {"name": "坏死性皮肤血管炎", "category": "脱疽", "aliases": [],
     "location": "下肢(双侧)", "morphology": "皮肤红斑、丘疹、肿胀、糜烂、流汁、坏死、结痂",
     "characteristics": "发病急进展快,愈合较慢,多种形态损害。", "differential": "与脱疽鉴别:皮肤血管炎为皮肤病损。",
     "prognosis": None, "western_equiv": "坏死性皮肤血管炎", "source": None, "is_dangerous": False,
     "treat": {"治则": "清热利湿,活血化瘀", "内治": "二妙丸合当归活血汤加减", "外治": "一效膏、生肌玉红膏外敷"}},
    {"name": "恶脉", "category": "脱疽", "aliases": ["赤脉", "青蛇便", "青蛇毒"],
     "location": "下肢浅层脉络(静脉)", "morphology": "沿浅层静脉走行,呈索条状红肿,灼热疼痛",
     "characteristics": "湿热下注气血凝滞,后期有索条状硬结色素沉着。", "differential": "与股白肿鉴别:恶脉为浅静脉炎。",
     "prognosis": None, "western_equiv": "血栓性浅静脉炎", "source": "《肘后备急方》", "is_dangerous": False,
     "treat": {"治则": "初期清热利湿解毒通络,后期活血化瘀通络散结", "内治": "初期三妙丸合五味消毒饮,后期桃红四物汤", "外治": "初期水调散、金黄散外敷,后期芒硝外敷"}},
    {"name": "股白肿", "category": "脱疽", "aliases": ["下肢深静脉血栓"],
     "location": "整个下肢", "morphology": "整个下肢突然肿胀沉痛,皮色不变",
     "characteristics": "术后产后外伤长期卧床气滞血瘀,左下肢多发,不化脓。", "differential": "与恶脉鉴别:股白肿为深静脉血栓。",
     "prognosis": "血栓脱落可致肺栓塞。", "western_equiv": "下肢血栓性深部静脉炎", "source": None, "is_dangerous": True,
     "treat": {"治则": "清热利湿,活血化瘀", "内治": "萆薢渗湿汤合桃红四物汤加减", "外治": "初期水调散、金黄膏外敷,后期熏洗药,急性期卧床患肢抬高"}},

    # ============ 第十三章 疮疡杂病 ============
    {"name": "发颐", "category": "疮疡杂病", "aliases": ["汗毒"],
     "location": "颐颌之间(腮腺)", "morphology": "颐颌之间焮热红肿疼痛,质地较硬,脓成不易外溃",
     "characteristics": "热性病后余毒未尽所致,严重者内陷。", "differential": "与颈痈鉴别:发颐在颐颌之间。",
     "prognosis": "重者内陷。", "western_equiv": "急性化脓性腮腺炎", "source": "《素问》", "is_dangerous": True,
     "treat": {"治则": "清热解毒,消肿散结", "内治": "普济消毒饮加减", "外治": "水调散、金黄膏、玉露膏外敷"}},
    {"name": "缠腰毒", "category": "疮疡杂病", "aliases": ["缠腰火丹"],
     "location": "腰部", "morphology": "下腰部带状红肿热痛,逐渐溃烂向两侧蔓延",
     "characteristics": "火毒湿热内蕴,伴口腔、阴部糜烂,深达筋肉。", "differential": "与蛇串疮鉴别:缠腰毒溃烂深大。",
     "prognosis": "不易愈合。", "western_equiv": "白塞氏病合并腰部感染", "source": None, "is_dangerous": True,
     "treat": {"治则": "和营托毒,清热利湿", "内治": "托里消毒散加减,脓腐尽八珍汤配六味地黄丸、西黄丸", "外治": "一效膏掺九一丹、八二丹,脓腐尽白玉膏掺生肌散"}},
    {"name": "皮肤坏疽", "category": "疮疡杂病", "aliases": [],
     "location": "躯干及四肢", "morphology": "皮肤瘙痒起泡坏疽结痂,水泡变黑呈干性结痂",
     "characteristics": "热毒挟湿客于肌肤,严重者指端坏死脱落,无寒热。", "differential": "与脱疽鉴别:皮肤坏疽为皮肤病损。",
     "prognosis": None, "western_equiv": "皮肤坏疽", "source": None, "is_dangerous": False,
     "treat": {"治则": "补益气血,兼清余毒", "内治": "四妙勇安汤加减,结痂脱落后八珍汤", "外治": "分期切痂,一效膏掺生肌散"}},
    {"name": "串珠疖", "category": "疮疡杂病", "aliases": ["陈肝疮"],
     "location": "手背及前臂", "morphology": "皮肤出现成串无痛性结节,渐溃破糜烂",
     "characteristics": "外伤后风湿热毒乘虚入侵,结节增多上串,久不收口。", "differential": "与蛇串疮鉴别:串珠疖为结节。",
     "prognosis": "久不收口。", "western_equiv": "孢子丝菌病", "source": None, "is_dangerous": False,
     "treat": {"治则": "祛风胜湿,清热和营", "内治": "消风散合五神汤加减", "外治": "未溃金黄膏、水调散,已溃一效膏、珍珠散掺提毒散"}},
    {"name": "蛇串疮", "category": "疮疡杂病", "aliases": ["缠腰火丹", "火腰带毒", "蛇丹"],
     "location": "腰部(带状分布)", "morphology": "成簇水泡带状分布,痛如针刺火烧",
     "characteristics": "肝火湿热,多发春秋季节,疱群之间皮肤正常。", "differential": "与缠腰毒鉴别:蛇串疮为疱疹。",
     "prognosis": None, "western_equiv": "带状疱疹", "source": "《外科大成·蛇串疮》", "is_dangerous": False,
     "treat": {"治则": "清肝泻热,利湿解毒", "内治": "龙胆泻肝汤加减", "外治": "疱疹四周沿皮针刺,后敷九一丹"}},
    {"name": "漆疮", "category": "疮疡杂病", "aliases": ["漆毒", "漆痱子"],
     "location": "接触漆毒部位", "morphology": "皮肤潮红肿胀,焮热成片,瘙痒灼痛,起红斑水泡",
     "characteristics": "先天禀性不耐,接触漆毒而发。", "differential": "与冻疮鉴别:漆疮因接触漆毒。",
     "prognosis": None, "western_equiv": "接触性皮炎", "source": "《诸病源候论·漆疮候》", "is_dangerous": False,
     "treat": {"治则": "清热解毒,利湿收敛", "内治": "化斑解毒汤加减", "外治": "一效膏或青黛散外敷"}},
    {"name": "阴肿", "category": "疮疡杂病", "aliases": ["阴茧"],
     "location": "妇女外阴部", "morphology": "外阴部焮红肿痛,形如蚕茧,按之波动,已成脓",
     "characteristics": "阴户损伤感染毒邪,左侧下方多见。", "differential": "与子痈鉴别:阴肿在女子外阴。",
     "prognosis": "易复发。", "western_equiv": "前庭大腺脓肿继发感染", "source": None, "is_dangerous": False,
     "treat": {"治则": "初期疏肝理脾清热利湿,中期透脓泄毒", "内治": "龙胆泻肝汤加减,中期加蒲公英、生黄芪、土茯苓", "外治": "初期水调散、玉露散外敷,中期切开引流"}},
    {"name": "子痰", "category": "疮疡杂病", "aliases": ["穿囊漏"],
     "location": "睾丸(附睾)", "morphology": "睾丸部肿块发展缓慢,化脓溃后脓汁稀薄挟絮状物",
     "characteristics": "易成漏愈合困难,子系增粗有串珠样改变。", "differential": "与子痈鉴别:子痰慢性结核,属阴证。",
     "prognosis": "易成漏。", "western_equiv": "慢性附睾结核", "source": None, "is_dangerous": False, "is_yang": False,
     "treat": {"治则": "初期解郁化痰软坚散结,成脓托里透脓,后期养荣化痰祛腐生肌", "内治": "初期橘核汤加减,成脓阳和汤,后期阳和汤加参芪夏枯草", "外治": "初期独角莲膏外贴,成脓切开引流外敷冲和膏"}},
    # ===== 新病种 =====
    {"name": "烧伤", "category": "烧伤", "aliases": ["烫伤", "火伤", "水火烫伤"],
     "location": "全身皮肤(任何部位)", "morphology": "皮肤红肿、起水泡、焦痂,按损伤深浅分I/II/III度",
     "characteristics": "烧伤包括汤烫、火伤及一切因气体、液体、固体及化学物体高热所致组织受伤;轻证仅伤肌表,重证火毒攻心。",
     "differential": "I度仅红肿,II度起水泡,III度焦痂深达肌层。", "prognosis": "重证可火毒攻心(败血症)危及生命。",
     "western_equiv": "烧伤", "source": "", "is_dangerous": True, "is_sores": False,
     "treat": {"治则": "清热解毒、养阴生津;火毒攻心者清热开窍", "内治": "初期生津解毒汤(经验方),火毒攻心者安宫牛黄丸、至宝丹", "外治": "I度、II度未破皮用清凉膏,各期用烧伤膏外敷"}},
    {"name": "红斑性狼疮", "category": "红斑性狼疮", "aliases": ["蝶疮"],
     "location": "面部及全身多系统", "morphology": "面部蝶形红斑,可累及皮肤、关节、肾等多系统",
     "characteristics": "西医认为属自身免疫性疾病;中医从整体辨证,以养阴解毒、宁心安神为法。",
     "differential": "与一般皮肤病鉴别:本病为多系统损害,非单纯皮损。", "prognosis": "慢性病程,需长期调治。",
     "western_equiv": "系统性红斑狼疮", "source": "", "is_dangerous": True, "is_sores": False,
     "treat": {"治则": "养阴解毒、宁心安神、健脾保肺", "内治": "首乌地黄汤(经验方)为基础方,善后长服二参地黄丸", "外治": "皮肤症状对症外用"}},
    {"name": "直肠溃疡", "category": "直肠溃疡", "aliases": ["肠痈", "直肠溃疡性结肠炎"],
     "location": "直肠、结肠", "morphology": "肠粘膜溃疡、糜烂出血,腹痛腹泻脓血便",
     "characteristics": "属祖国医学广义肠痈范围;辨证多见下焦湿热郁久化腐,或脾胃两虚、湿热乘虚下积肠道。",
     "differential": "与痢疾鉴别:痢疾以脓血便为主,本病经肠镜证实溃疡。", "prognosis": "可反复发作。",
     "western_equiv": "直肠溃疡/溃疡性结肠炎", "source": "", "is_dangerous": False, "is_sores": False,
     "treat": {"治则": "清利湿热、排脓解毒,或健脾除湿", "内治": "银花红藤败酱散(经验方)加味", "外治": "内服为主,注意饮食调护"}},
    {"name": "皮肤瘙痒证", "category": "皮肤病", "aliases": ["皮肤病", "痒症"],
     "location": "全身皮肤", "morphology": "皮肤瘙痒,可伴丘疹、斑块、水泡,抓破流黄水",
     "characteristics": "以瘙痒为特点,痒症多属「风」,外风为条件、内风(血虚、血燥、血热生风)为根本;分风热、湿热、血热、血燥、血瘀、血虚、风寒七型。",
     "differential": "与疥疮鉴别:疥疮有疥虫、夜间奇痒、有传染性。", "prognosis": "缠绵难愈,易反复。",
     "western_equiv": "皮肤瘙痒症、湿疹、荨麻疹等", "source": "", "is_dangerous": False, "is_sores": False,
     "treat": {"治则": "养血祛风、解毒止痒", "内治": "祛风活血汤(经验方)为基础方,随证加减", "外治": "加味苦参汤煎水外洗"}},
    {"name": "头癣", "category": "头癣", "aliases": ["秃疮", "肥疮", "白癣"],
     "location": "头部", "morphology": "头皮脱屑、脱发,分秃疮(白癣)、肥疮两类",
     "characteristics": "好发于学龄儿童,男孩多于女孩;秃疮相当于西医白癣,肥疮为黄癣。",
     "differential": "与斑秃鉴别:斑秃为局限性脱发无鳞屑,头癣有鳞屑断发。", "prognosis": "可治愈,需注意卫生防复发。",
     "western_equiv": "头癣(白癣、黄癣)", "source": "", "is_dangerous": False, "is_sores": False,
     "treat": {"治则": "疏风清热、杀虫止痒", "内治": "祛风活血汤加减", "外治": "淘花汤煎水洗头,秃疮散外敷"}},
]
